version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - ./processed_data:/app/processed_data
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-key-for-development
      - DATABASE_URL=sqlite:///db.sqlite3
      - LANCEDB_PATH=/app/processed_data/lancedb_directory
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend