# Generated by Django 4.2.20 on 2025-04-26 07:22

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('authors', core.models.JSONField(default='[]')),
                ('categories', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('journal_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('filters', core.models.JSONField(default=dict)),
                ('result_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPaperInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('save', 'Save'), ('download', 'Download'), ('like', 'Like'), ('dislike', 'Dislike')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='core.paper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_interactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity_score', models.FloatField()),
                ('recommendation_date', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.CharField(default='allenai-specter', max_length=50)),
                ('recommended_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_for', to='core.paper')),
                ('source_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_made', to='core.paper')),
            ],
        ),
        migrations.CreateModel(
            name='PaperView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='core.paper')),
            ],
        ),
        migrations.CreateModel(
            name='PaperEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('vector_id', models.CharField(max_length=100)),
                ('dimensions', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='core.paper')),
            ],
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['categories'], name='core_paper_categor_3dad13_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['update_date'], name='core_paper_update__8d5e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='usersearch',
            index=models.Index(fields=['user'], name='core_userse_user_id_a7567b_idx'),
        ),
        migrations.AddIndex(
            model_name='usersearch',
            index=models.Index(fields=['session_id'], name='core_userse_session_969a22_idx'),
        ),
        migrations.AddIndex(
            model_name='usersearch',
            index=models.Index(fields=['timestamp'], name='core_userse_timesta_3070ef_idx'),
        ),
        migrations.AddIndex(
            model_name='userpaperinteraction',
            index=models.Index(fields=['user', 'interaction_type'], name='core_userpa_user_id_c8df6f_idx'),
        ),
        migrations.AddIndex(
            model_name='userpaperinteraction',
            index=models.Index(fields=['paper', 'interaction_type'], name='core_userpa_paper_i_9c9c64_idx'),
        ),
        migrations.AddIndex(
            model_name='userpaperinteraction',
            index=models.Index(fields=['timestamp'], name='core_userpa_timesta_96fdc2_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['similarity_score'], name='core_recomm_similar_60ce0a_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['recommendation_date'], name='core_recomm_recomme_9f9fae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('source_paper', 'recommended_paper', 'model_name')},
        ),
        migrations.AddIndex(
            model_name='paperview',
            index=models.Index(fields=['session_id'], name='core_paperv_session_9a70b4_idx'),
        ),
        migrations.AddIndex(
            model_name='paperview',
            index=models.Index(fields=['timestamp'], name='core_paperv_timesta_276b75_idx'),
        ),
        migrations.AddIndex(
            model_name='paperembedding',
            index=models.Index(fields=['model_name'], name='core_papere_model_n_5f4201_idx'),
        ),
        migrations.AddIndex(
            model_name='paperembedding',
            index=models.Index(fields=['vector_id'], name='core_papere_vector__4a600f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paperembedding',
            unique_together={('paper', 'model_name')},
        ),
    ]
